### ISSUE TITLE
Changing Orientation Causes the Page to Reload

### ISSUE THREAD

**Issue by landry314** [gsurrel/FacebookNotifications#21]
If I am in the middle of writing a message then switch from portrait to landscape orientation then the page reloads completely and I not only lose what I was typing but I have to then find my friend again to start a new message.

Why does an orientation switch cause a total reload? This isn't how most apps work.

**Comment by gsurrel** [comment]
It's indeed not the expected behavior because the "browser" part of the app was initially only for logging-in. The total reload is a side effect of how Android works and I have no specific code to prevent that.

In the meantime, before getting a clean solution, I will lock the orientation even if I don't like that: it's better to be a little annoyed than loosing the whole text and page.

**Comment by gsurrel** [comment]
I've found a nice way, it works like a charm :)
